<a href="https://colab.research.google.com/github/Isabela-Tellez/BootCampIA_Python/blob/main/Numpy/NumpySession%232.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🐍 Clase Maestra: Algebra Lineal NumPy

In [ ]:
#Importe Libreria NumPy
import numpy as np
np.__version__

'2.0.2'

## 🎤 **Temática: Slicing, Broadcasting y el misterio de la cafetería**

Hoy se van a hacer tres cosas:

  1.   cortar datos (slicing)
  2.   aplicar reglas a muchos datos (broadcasting)
  1.   resolver un problema real como si fuéramos un equipo de Data Science (sistemas lineales).”


### **Warm-up rápido: slicing y broadcasting**

*   Elemento de lista
*   Elemento de lista



**Idea:** En Data Science casi todo es una **matriz** y necesitamos seleccionar partes (slicing) y operar sin bucles (broadcasting).

**¿Qué representa cada fila y cada columna en un dataset?**

- Filas: ejemplos  
- Columnas: variables/features

ALGEBRA LINEAL NUMPY

In [ ]:
#Creación primer Array
datos = np.array([10, 20, 30, 40])
datos

array([10, 20, 30, 40])

In [ ]:
#Valor:     10   20   30   40
#Posición:   0    1    2    3

In [ ]:
#Muestreo de las 3 primera posiciones
datos[0:3]

array([10, 20, 30])

In [ ]:
#Muestreo desde la primera posicion hasta la tercera
datos[1:4]


array([20, 30, 40])

**MATRICES (DONDE ESTÁ EL PODER REAL)**

In [23]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
matriz

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [24]:

                          #Columna

#Valor:     10   20   30      0
#           40   50   60      1
#           70   80   90      2

#Fila:       0    1    2

In [25]:
#Extraer la primera fila
matriz[0]

array([10, 20, 30])

In [29]:
#Antes de la coma(,) especifica la columna en este caso 2 y despues de la coma (,) indica la fila en este caso 1
matriz[0:3,1]

array([20, 50, 80])

In [27]:
#Extraer una columna
# : Muestra todos los elementos y el 1 indica cuál columna se quiere mostrar
matriz[:,1]

array([20, 50, 80])

In [28]:
#Mostrar esta matriz
#   10, 20
#   40, 50
matriz[0:2, 0:2]

array([[10, 20],
       [40, 50]])

In [ ]:
#Mostrar esta matriz
#   20, 30
#   50, 60
matriz[0:2, 1:3]

array([[20, 30],
       [50, 60]])

**CREACIÓN DE CAFETERIA DIGITAL**

In [ ]:
#Creación de la matriz de la cafetería
#[cafés vendidos, croissants vendidos]
ventas = np.array([
    [10,5],#lunes
    [15,8],#martes
    [12,6],#miercoles
    [20,12],#jueves
    [25,15],#viernes
])
print("Nuestra tabla de ventas:")
print(ventas)

Nuestra tabla de ventas:
[[10  5]
 [15  8]
 [12  6]
 [20 12]
 [25 15]]


## **Slicing:** El Arte de la Linterna

In [ ]:
#Mostar la primera fila
ventas[0]

array([10,  5])

In [ ]:
#Mostar la segunda columna
croissants_vendidos = ventas[:,1]
print(croissants_vendidos)

[ 5  8  6 12 15]


In [ ]:
ventas_inicio_semana = ventas [0:2, :]
print("Solo Lunes y Martes")
print(ventas_inicio_semana)

Solo Lunes y Martes
[[10  5]
 [15  8]]


---
### **Array Broadcasting**

**VECTOR 1D
MATRIZ 2 o más Dimensiones**

Broadcasting es una característica en Numpy que permite ejecutar operaciones con arrays de diferentes formas y tamaños sin recorrer explicitamente elementos. Broadcasting automáticamente expande pequeños arrays para emparejar/encajar redimensionarlos al tamaño del grande.

**Reglas**
- Si el array es diferente en dimensiones, el pequeño es


In [ ]:
a = np.array([1, 2, 3])
b = 2

#SUMA
#Suma a cada elemento del array 2
result = a + b
print(result)

[3 4 5]


In [ ]:
#MATRIZ
#Le suma la dimension del arr a cada dimension de la matriz
arr = np.array([1, 2, 3])
matriz =np.array([
    [1, 2, 3],
    [4, 5, 6]])

result = arr + matriz
print(result)

[[2 4 6]
 [5 7 9]]


---

## El Megáfono Matemático

In [ ]:
#Creación de la matriz de la cafetería
#[cafés vendidos, croissants vendidos]
ventas = np.array([
    [10,5],#lunes
    [15,8],#martes
    [12,6],#miercoles
    [20,12],#jueves
    [25,15],#viernes
])
print("Nuestra tabla de ventas:")
print(ventas)

Nuestra tabla de ventas:
[[10  5]
 [15  8]
 [12  6]
 [20 12]
 [25 15]]


In [ ]:
#Sumar .50 a cada precio
ventas_ajuste = ventas + 0.50
print("Precios ajustados por 0.50")
print(ventas_ajuste)

Precios ajustados por 0.50
[[10.5  5.5]
 [15.5  8.5]
 [12.5  6.5]
 [20.5 12.5]
 [25.5 15.5]]


---

## **Sistemas Lineales**: El Misterio del Ticket Borrado

Imaginemos que el dueño de la cafetería ha perdido la lista de precios y solo cuenta con los siguientes datos:

- Lunes: vendió 2 Cafés y 1 Croissant para un total de 5€
- Martes: vendió 1 Café y 1 Croissant para un total de 3€

¿Cuánto vale el Café?
¿Cuánto el Croissant?

In [ ]:
#Código Sistemas Lineales

#A Array
A = np.array([
    [2,1],#lunes
    [1,1],#martes
])

#B De lo que se paga
B = np.array([5, 3])

result = np.linalg.solve(A, B)
print(f"Precio Café: {result[0]}")
print(f"Precio Croissant: {result[1]}")

Precio Café: 2.0
Precio Croissant: 1.0


---


# **🛠️ Bloque Práctico** 🧩


## Niveles
🟢 Verde → 🟡 Amarillo → 🔴 Rojo → 🏆 Reto final



## 🟢 Nivel Verde – Slicing y broadcasting (calentamiento)

### Ejercicio 1
Crea una matriz 5x3 con números a elección. Extrae: (a) primera fila, (b) última columna, (c) filas 2 a 4.

**Interpretación (1 frase):**

In [39]:
#Importe Libreria NumPy
import numpy as np

#Creación de la matriz
matriz = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45],
    [50, 55, 60],
    [65, 70, 75]
])
print (f"Matriz: \n{matriz}")

#Mostar la primera fila
print (f"\nMatriz 1ra fila: {matriz[0]}")

#Mostrar última columna
print (f"\nMatriz última columna: {matriz[:,2]}")

#Mostrar filas 2 a 4
print (f"\nMatriz filas 2 a 4: \n{matriz[1:4, 0:3]}")

Matriz: 
[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]
 [65 70 75]]

Matriz 1ra fila: [ 5 10 15]

Matriz última columna: [15 30 45 60 75]

Matriz filas 2 a 4: 
[[20 25 30]
 [35 40 45]
 [50 55 60]]


Ejercicio 2
Dada una matriz X, resta la media de cada columna usando broadcasting. Pista: X - X.mean(axis=0)

Interpretación (1 frase):